@host = http://localhost:5074
@json = application/json

### PROIEZIONI ！ Lista
GET {{host}}/proiezioni

### PROIEZIONI ！ Singola
GET {{host}}/proiezioni/1

### PROIEZIONI ！ Crea
POST {{host}}/proiezioni
Content-Type: {{json}}

{
  "titolo": "Interstellar",
  "durataMin": 169,
  "genere": "Sci-Fi",
  "nazionalita": "USA",
  "lingua": "EN",
  "descrizione": "Viaggio nello spazio-tempo",
  "sala": "Sala 3",
  "orarioInizio": "2025-09-12T21:00:00",
  "postiTotali": 140,
  "prezzo": 10.50
}

### PROIEZIONI ！ Aggiorna (parziale)
PUT {{host}}/proiezioni/1
Content-Type: {{json}}

{
  "prezzo": 8.90,
  "postiTotali": 130
}

### PROIEZIONI ！ Elimina
DELETE {{host}}/proiezioni/2


# ==========================
#     BIGLIETTI
# ==========================

### BIGLIETTI ！ Lista
GET {{host}}/biglietti

### BIGLIETTI ！ Acquista (prenotazione)
POST {{host}}/biglietti/acquista
Content-Type: {{json}}

{
  "proiezioneId": 1,
  "fila": "B",
  "numero": 7
}

### BIGLIETTI ！ Dettaglio (sostituisci 1 con l'Id reale)
GET {{host}}/biglietti/1

### BIGLIETTI ！ Acquisto stesso posto (atteso 409 Conflict)
POST {{host}}/biglietti/acquista
Content-Type: {{json}}

{
  "proiezioneId": 1,
  "fila": "B",
  "numero": 7
}

### PROIEZIONI ！ Elimina con biglietti esistenti (atteso 409 Conflict)
DELETE {{host}}/proiezioni/1

### BIGLIETTI ！ Cancella biglietto (sostituisci 1 con l'Id reale)
DELETE {{host}}/biglietti/1
